apiVersion: v1
kind: Service
metadata:
  name: osm-tile
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: osm-tile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osm-tile-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osm-tile
      track: canary
  template:
    metadata:
      labels:
        app: osm-tile
        track: canary
    spec:
      containers:
      - name: osm-tile-k8s
        image: unifon/osm-tileserver:v1.0.4
        env:
        - name: TILESERVER_MODE
          value: CREATE
        - name: TILESERVER_DATA_LABEL
          value: tile-norway-20201031
        - name: TILESERVER_STORAGE_PATH
          value: "/mnt/azure"
        - name: ALLOW_CORS
          value: enabled
        volumeMounts:
        - name: azure
          mountPath: /mnt/azure
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
      volumes:
      - name: azure
        azureFile:
          secretName: azure-storage-secret
          shareName: azure
          readOnly: false
